#!/bin/bash


echo 

                                                                              
 ###### ##### #    #   ##   #    # # #    #  ####  #####   ##   #      #      
 #        #   #    #  #  #  ##   # # ##   # #        #    #  #  #      #      
 #####    #   ###### #    # # #  # # # #  #  ####    #   #    # #      #      
 #        #   #    # ###### #  # # # #  # #      #   #   ###### #      #      
 #        #   #    # #    # #   ## # #   ## #    #   #   #    # #      #      
 ######   #   #    # #    # #    # # #    #  ####    #   #    # ###### ###### 
                                                                              

sleep 5


sudo pacman -S git go

git clone https://aur.archlinux.org/yay
cd yay
makepkg -si

yay -S zsh fastfetch vesktop cmatrix-git asciiquarium-transparent cava spotify ttf-jetbrains-mono ttf-jetbrains-nerd extension-manager firefox flatpak bpytop neovim

sleep 3

echo "we're done with the apps! now time to install games so that you can play!"

sleep 5 

flatpak install sober srb2

echo "ALL DONE! ENJOY ARCH LINUX!" 
